sudo: required
language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
  - pip install numpy
  - pip install scipy
  - pip install scikit-learn
  - pip install coveralls
  - python setup.py install
# command to run tests
script: nosetests
